export const ASSIGNMENT_TYPE_OPTIONS = ['Bài tập', 'Đề thi'];

export const LEVEL_OPTIONS = [
  'Lớp 1',
  'Lớp 2',
  'Lớp 3',
  'Lớp 4',
  'Lớp 5',
  'Lớp 6',
  'Lớp 7',
  'Lớp 8',
  'Lớp 9',
  'Lớp 10',
  'Lớp 11',
  'Lớp 12',
  'IELTS',
  'TOEIC',
];

export const DIFFICULTY_OPTIONS = ['Cơ bản', 'Trung bình', 'Nâng cao'];

export const SKILL_OPTIONS = ['Nghe', 'Đọc', 'Viết'];

export const DELIVERY_STATUS_OPTIONS = ['Nháp', 'Đã tạo', 'Đã giao', 'Đã đóng'];

export const QUESTION_BANK_STATUS_OPTIONS = ['Nháp', 'Đang sử dụng', 'Ngừng sử dụng'];

export const EXERCISE_STATUS_OPTIONS = ['Nháp', 'Chờ duyệt', 'Đã duyệt', 'Ngừng sử dụng'];

export const QUESTION_FORMATS_BY_SKILL = {
  Nghe: [
    'Trả lời ngắn',
    'Trắc nghiệm 1 đáp án',
    'Trắc nghiệm nhiều đáp án',
    'Hoàn thiện câu',
    'Nối các phần tương ứng',
    'Phân loại',
  ],
  Đọc: [
    'Trắc nghiệm 1 đáp án',
    'Trắc nghiệm nhiều đáp án',
    'Điền từ vào chỗ trống/khuyết',
    'Điền từ vào chỗ trống tương ứng từ một danh sách từ cho trước',
    'Cho dạng đúng của từ',
    'Nối ghép các phần tương ứng',
    'Tìm một từ dùng trong nhiều câu',
    'Trả lời ngắn',
    'Chèn câu vào đoạn văn',
    'Tìm và sửa lỗi sai',
    'Viết lại câu',
    'Giải thích thành ngữ hoặc cụm từ',
  ],
  Viết: [],
};

export const MOCK_CLASSES = [
  { id: 'CLS-IELTS-01', name: 'IELTS Foundation T3-T5-T7', level: 'IELTS', teacher: 'Cô Minh', students: 18 },
  { id: 'CLS-IELTS-02', name: 'IELTS Intensive T2-T4-T6', level: 'IELTS', teacher: 'Thầy Khoa', students: 16 },
  { id: 'CLS-TOEIC-01', name: 'TOEIC 650+ Sáng', level: 'TOEIC', teacher: 'Cô Ngân', students: 22 },
  { id: 'CLS-G10-01', name: 'Lớp 10A1 tăng cường', level: 'Lớp 10', teacher: 'Cô Phương', students: 28 },
  { id: 'CLS-G09-01', name: 'Lớp 9 chuyên đề Reading', level: 'Lớp 9', teacher: 'Thầy Huy', students: 24 },
];

export const MOCK_STUDENTS = [
  { id: 'STD-001', name: 'Nguyễn Mai Anh', classId: 'CLS-IELTS-01', level: 'IELTS' },
  { id: 'STD-002', name: 'Trần Gia Hưng', classId: 'CLS-IELTS-01', level: 'IELTS' },
  { id: 'STD-003', name: 'Phạm Hoài Nam', classId: 'CLS-IELTS-02', level: 'IELTS' },
  { id: 'STD-004', name: 'Đỗ Minh Khôi', classId: 'CLS-TOEIC-01', level: 'TOEIC' },
  { id: 'STD-005', name: 'Lê Kim Ngọc', classId: 'CLS-G10-01', level: 'Lớp 10' },
];

export const MOCK_ASSIGNMENTS = [
  {
    id: 'ASN-001',
    code: 'EX-IELTS-RD-001',
    title: 'Đề đọc hiểu IELTS Unit 3 - Đợt 1',
    type: 'Đề thi',
    level: 'IELTS',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    totalItems: 6,
    durationMinutes: 45,
    status: 'Đã giao',
    createdAt: '2026-07-01T08:30:00',
    targetClasses: ['CLS-IELTS-01'],
    targetStudents: [],
    studentsDone: 14,
    averageScore: 7.8,
  },
  {
    id: 'ASN-002',
    code: 'BT-TOEIC-LS-002',
    title: 'Bài nghe TOEIC Part 2 - luyện tập',
    type: 'Bài tập',
    level: 'TOEIC',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    totalItems: 5,
    durationMinutes: 20,
    status: 'Đã giao',
    createdAt: '2026-07-02T10:15:00',
    targetClasses: ['CLS-TOEIC-01'],
    targetStudents: [],
    studentsDone: 18,
    averageScore: 8.4,
  },
  {
    id: 'ASN-003',
    code: 'EX-G10-RD-003',
    title: 'Đề đọc hiểu lớp 10 - môi trường',
    type: 'Đề thi',
    level: 'Lớp 10',
    difficulty: 'Nâng cao',
    skill: 'Đọc',
    totalItems: 4,
    durationMinutes: 40,
    status: 'Đã tạo',
    createdAt: '2026-07-03T09:45:00',
    targetClasses: [],
    targetStudents: [],
    studentsDone: 0,
    averageScore: 0,
  },
  {
    id: 'ASN-004',
    code: 'BT-IELTS-WR-004',
    title: 'Bài viết IELTS Task 2 - Opinion',
    type: 'Bài tập',
    level: 'IELTS',
    difficulty: 'Nâng cao',
    skill: 'Viết',
    totalItems: 2,
    durationMinutes: 60,
    status: 'Nháp',
    createdAt: '2026-07-03T15:00:00',
    targetClasses: [],
    targetStudents: [],
    studentsDone: 0,
    averageScore: 0,
  },
];

export const MOCK_QUESTION_BANKS = [
  {
    id: 'QB-IELTS-RD-01',
    code: 'NHD-IELTS-RD-01',
    name: 'Ngân hàng đọc hiểu IELTS Unit 3',
    level: 'IELTS',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    unit: 'Unit 3',
    description: 'Ngân hàng đọc hiểu dùng để sinh đề IELTS Reading mức trung bình.',
    status: 'Đang sử dụng',
    createdAt: '2026-06-20T08:00:00',
    exercises: [
      {
        id: 'EX-RD-001',
        code: 'BT-RD-001',
        title: 'Reading MCQ - Urban Transport',
        questionFormat: 'Trắc nghiệm 1 đáp án',
        unit: 'Unit 3',
        content: 'Đọc đoạn văn về giao thông đô thị và chọn đáp án đúng cho từng ý chính.',
        audioUrl: '',
        imageUrl: '',
        note: 'Dùng cho đề đọc hiểu IELTS mức trung bình.',
        status: 'Đã duyệt',
        createdAt: '2026-06-20T09:10:00',
        childQuestions: [
          {
            id: 'CQ-RD-001-1',
            prompt: 'Ý chính của đoạn 1 là gì?',
            answerType: 'single_choice',
            options: [
              { id: 'A', label: 'A', text: 'Mở rộng tàu điện ngầm', isCorrect: true },
              { id: 'B', label: 'B', text: 'Giảm thuế nhiên liệu', isCorrect: false },
              { id: 'C', label: 'C', text: 'Xây thêm bãi đỗ xe', isCorrect: false },
              { id: 'D', label: 'D', text: 'Cấm xe đạp', isCorrect: false },
            ],
            acceptedAnswers: [],
            score: 1,
            explanation: 'Đoạn 1 nhấn mạnh vai trò của tàu điện ngầm.',
          },
        ],
      },
      {
        id: 'EX-RD-002',
        code: 'BT-RD-002',
        title: 'Reading Short Answer - Library Notice',
        questionFormat: 'Trả lời ngắn',
        unit: 'Unit 3',
        content: 'Đọc thông báo của thư viện thành phố và trả lời ngắn.',
        audioUrl: '',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-21T08:20:00',
        childQuestions: [
          {
            id: 'CQ-RD-002-1',
            prompt: 'Thư viện đóng cửa vào ngày nào?',
            answerType: 'short_text',
            options: [],
            acceptedAnswers: ['Sunday', 'Chủ nhật'],
            score: 1,
            explanation: 'Thông báo ghi rõ thư viện đóng cửa vào Chủ nhật.',
          },
        ],
      },
      {
        id: 'EX-RD-003',
        code: 'BT-RD-003',
        title: 'Gap-fill Passage - Climate Policy',
        questionFormat: 'Điền từ vào chỗ trống/khuyết',
        unit: 'Unit 3',
        content: 'Đoạn văn về chính sách khí hậu với các chỗ trống cần điền.',
        audioUrl: '',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-22T11:00:00',
        childQuestions: [
          {
            id: 'CQ-RD-003-1',
            prompt: 'Điền từ phù hợp vào chỗ trống.',
            answerType: 'gap_fill',
            options: [],
            acceptedAnswers: ['emissions'],
            score: 1,
            explanation: 'Từ cần điền là emissions.',
            passage: 'The city aims to reduce ____ by 30 percent before 2030.',
          },
        ],
      },
      {
        id: 'EX-RD-004',
        code: 'BT-RD-004',
        title: 'Insert Sentence - Smart Mobility',
        questionFormat: 'Chèn câu vào đoạn văn',
        unit: 'Unit 3',
        content: 'Đoạn văn về smart mobility và câu cần chèn.',
        audioUrl: '',
        imageUrl: '',
        note: '',
        status: 'Chờ duyệt',
        createdAt: '2026-06-23T13:40:00',
        childQuestions: [
          {
            id: 'CQ-RD-004-1',
            prompt: 'Chọn vị trí đúng để chèn câu vào đoạn văn.',
            answerType: 'insert_sentence',
            options: [],
            acceptedAnswers: [],
            score: 1,
            explanation: '',
            passage: 'Sentence 1. Sentence 2. Sentence 3. Sentence 4.',
            insertSentence: 'This shift also improves the quality of public transport.',
            correctPosition: 'Sau câu 2',
          },
        ],
      },
    ],
  },
  {
    id: 'QB-TOEIC-LS-01',
    code: 'NHD-TOEIC-LS-01',
    name: 'Ngân hàng nghe TOEIC Part 2 - Part 3',
    level: 'TOEIC',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    unit: 'Part 2',
    description: 'Ngân hàng nghe dùng cho bài tập ngắn và đề luyện TOEIC cơ bản.',
    status: 'Đang sử dụng',
    createdAt: '2026-06-18T09:00:00',
    exercises: [
      {
        id: 'EX-LS-001',
        code: 'BT-LS-001',
        title: 'Short Answer - Reception Desk',
        questionFormat: 'Trả lời ngắn',
        unit: 'Part 2',
        content: 'Nghe hội thoại tại quầy lễ tân và trả lời ngắn.',
        audioUrl: 'https://example.com/audio/reception.mp3',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-18T09:30:00',
        childQuestions: [
          {
            id: 'CQ-LS-001-1',
            prompt: 'Khách đến để gặp ai?',
            answerType: 'short_text',
            options: [],
            acceptedAnswers: ['Mr. Brown', 'Brown'],
            score: 1,
            explanation: 'Người khách đến để gặp Mr. Brown.',
          },
        ],
      },
      {
        id: 'EX-LS-002',
        code: 'BT-LS-002',
        title: 'Listening MCQ - Team Meeting',
        questionFormat: 'Trắc nghiệm 1 đáp án',
        unit: 'Part 2',
        content: 'Nghe thông báo cuộc họp và chọn đáp án đúng.',
        audioUrl: 'https://example.com/audio/meeting.mp3',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-19T10:10:00',
        childQuestions: [
          {
            id: 'CQ-LS-002-1',
            prompt: 'Cuộc họp bắt đầu lúc mấy giờ?',
            answerType: 'single_choice',
            options: [
              { id: 'A', label: 'A', text: '8:00', isCorrect: false },
              { id: 'B', label: 'B', text: '8:30', isCorrect: true },
              { id: 'C', label: 'C', text: '9:00', isCorrect: false },
              { id: 'D', label: 'D', text: '9:30', isCorrect: false },
            ],
            acceptedAnswers: [],
            score: 1,
            explanation: 'Thông báo nêu rõ cuộc họp bắt đầu lúc 8:30.',
          },
        ],
      },
      {
        id: 'EX-LS-003',
        code: 'BT-LS-003',
        title: 'Listening Multi Choice - Hotel Booking',
        questionFormat: 'Trắc nghiệm nhiều đáp án',
        unit: 'Part 3',
        content: 'Nghe cuộc gọi đặt phòng và chọn các thông tin đúng.',
        audioUrl: 'https://example.com/audio/hotel.mp3',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-20T07:45:00',
        childQuestions: [
          {
            id: 'CQ-LS-003-1',
            prompt: 'Khách yêu cầu những tiện ích nào?',
            answerType: 'multi_choice',
            options: [
              { id: 'A', label: 'A', text: 'Late check-in', isCorrect: true },
              { id: 'B', label: 'B', text: 'Sea view', isCorrect: false },
              { id: 'C', label: 'C', text: 'Airport pickup', isCorrect: true },
              { id: 'D', label: 'D', text: 'Breakfast only', isCorrect: false },
            ],
            acceptedAnswers: [],
            score: 1,
            explanation: 'Khách yêu cầu late check-in và airport pickup.',
          },
        ],
      },
      {
        id: 'EX-LS-004',
        code: 'BT-LS-004',
        title: 'Matching - Department Requests',
        questionFormat: 'Nối các phần tương ứng',
        unit: 'Part 3',
        content: 'Nghe các yêu cầu từ từng phòng ban và nối thông tin phù hợp.',
        audioUrl: 'https://example.com/audio/department.mp3',
        imageUrl: '',
        note: '',
        status: 'Đã duyệt',
        createdAt: '2026-06-20T14:25:00',
        childQuestions: [
          {
            id: 'CQ-LS-004-1',
            prompt: 'Nối phòng ban với yêu cầu phù hợp.',
            answerType: 'matching',
            options: [],
            acceptedAnswers: [],
            score: 1,
            explanation: '',
            leftItems: ['Sales', 'HR'],
            rightItems: ['Projector', 'Training room'],
            matchingPairs: [
              { left: 'Sales', right: 'Projector' },
              { left: 'HR', right: 'Training room' },
            ],
          },
        ],
      },
      {
        id: 'EX-LS-005',
        code: 'BT-LS-005',
        title: 'Classification - Customer Feedback',
        questionFormat: 'Phân loại',
        unit: 'Part 3',
        content: 'Nghe phản hồi của khách hàng và phân loại theo nhóm.',
        audioUrl: 'https://example.com/audio/feedback.mp3',
        imageUrl: '',
        note: '',
        status: 'Nháp',
        createdAt: '2026-06-21T16:15:00',
        childQuestions: [
          {
            id: 'CQ-LS-005-1',
            prompt: 'Phân loại ý kiến khách hàng vào nhóm phù hợp.',
            answerType: 'classification',
            options: [],
            acceptedAnswers: [],
            score: 1,
            explanation: '',
            classificationGroups: ['Tích cực', 'Cần cải thiện'],
            classificationItems: [
              { value: 'Fast response', group: 'Tích cực' },
              { value: 'Long waiting time', group: 'Cần cải thiện' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'QB-IELTS-WR-01',
    code: 'NHD-IELTS-WR-01',
    name: 'Ngân hàng viết IELTS Task 2',
    level: 'IELTS',
    difficulty: 'Nâng cao',
    skill: 'Viết',
    unit: 'Task 2',
    description: 'Ngân hàng viết đang ở mức placeholder, chờ cấu hình chi tiết dạng câu hỏi.',
    status: 'Nháp',
    createdAt: '2026-06-25T10:00:00',
    exercises: [
      {
        id: 'EX-WR-001',
        code: 'BT-WR-001',
        title: 'Opinion Essay - Technology in Education',
        questionFormat: 'Viết bài luận',
        unit: 'Task 2',
        content: 'Some people think technology makes students less creative. To what extent do you agree?',
        audioUrl: '',
        imageUrl: '',
        note: 'Placeholder cho kỹ năng viết.',
        status: 'Nháp',
        createdAt: '2026-06-25T10:20:00',
        childQuestions: [
          {
            id: 'CQ-WR-001-1',
            prompt: 'Viết bài luận khoảng 250 từ.',
            answerType: 'essay',
            options: [],
            acceptedAnswers: [],
            score: 1,
            explanation: '',
            sampleAnswer: '',
            gradingGuide: 'Chấm theo tiêu chí task response, coherence, lexical resource và grammar.',
          },
        ],
      },
    ],
  },
];
