export const ASSIGNMENT_TYPE_OPTIONS = ['Bài tập', 'Đề thi'];

export const LEVEL_OPTIONS = [
  'Lớp 1',
  'Lớp 2',
  'Lớp 3',
  'Lớp 4',
  'Lớp 5',
  'Lớp 6',
  'Lớp 7',
  'Lớp 8',
  'Lớp 9',
  'Lớp 10',
  'Lớp 11',
  'Lớp 12',
  'IELTS',
  'TOEIC',
];

export const DIFFICULTY_OPTIONS = ['Cơ bản', 'Trung bình', 'Nâng cao'];

export const SKILL_OPTIONS = ['Nghe', 'Đọc', 'Viết'];

export const DELIVERY_STATUS_OPTIONS = ['Nháp', 'Đã sinh đề', 'Đã giao', 'Đã đóng'];

export const BANK_STATUS_OPTIONS = ['Nháp', 'Sẵn sàng', 'Đang dùng'];

export const QUESTION_FORMATS_BY_SKILL = {
  Nghe: [
    'Trả lời ngắn',
    'Trắc nghiệm 1 đáp án',
    'Trắc nghiệm nhiều đáp án',
    'Hoàn thiện câu',
    'Nối các phần tương ứng',
    'Phân loại',
  ],
  Đọc: [
    'Trắc nghiệm 1 đáp án',
    'Trắc nghiệm nhiều đáp án',
    'Điền từ vào chỗ trống/khuyết',
    'Điền từ vào chỗ trống từ danh sách cho trước',
    'Cho dạng đúng của từ',
    'Nối ghép các phần tương ứng',
    'Tìm một từ dùng trong nhiều câu',
    'Trả lời ngắn',
    'Chèn câu vào đoạn văn',
    'Tìm và sửa lỗi sai',
    'Viết lại câu',
    'Giải thích thành ngữ hoặc cụm từ',
  ],
  Viết: ['Viết câu', 'Viết đoạn văn', 'Viết bài luận', 'Viết lại câu'],
};

export const MOCK_CLASSES = [
  { id: 'CLS-IELTS-01', name: 'IELTS Foundation T3-T5-T7', level: 'IELTS', teacher: 'Cô Minh', students: 18 },
  { id: 'CLS-IELTS-02', name: 'IELTS Intensive T2-T4-T6', level: 'IELTS', teacher: 'Thầy Khoa', students: 16 },
  { id: 'CLS-TOEIC-01', name: 'TOEIC 650+ Sáng', level: 'TOEIC', teacher: 'Cô Ngân', students: 22 },
  { id: 'CLS-G10-01', name: 'Lớp 10A1 tăng cường', level: 'Lớp 10', teacher: 'Cô Phương', students: 28 },
  { id: 'CLS-G09-01', name: 'Lớp 9 chuyên đề Reading', level: 'Lớp 9', teacher: 'Thầy Huy', students: 24 },
  { id: 'CLS-G06-01', name: 'Lớp 6 nền tảng', level: 'Lớp 6', teacher: 'Cô Lan', students: 26 },
];

export const MOCK_STUDENTS = [
  { id: 'STD-001', name: 'Nguyễn Mai Anh', classId: 'CLS-IELTS-01', level: 'IELTS' },
  { id: 'STD-002', name: 'Trần Gia Hưng', classId: 'CLS-IELTS-01', level: 'IELTS' },
  { id: 'STD-003', name: 'Phạm Hoài Nam', classId: 'CLS-IELTS-02', level: 'IELTS' },
  { id: 'STD-004', name: 'Đỗ Minh Khôi', classId: 'CLS-TOEIC-01', level: 'TOEIC' },
  { id: 'STD-005', name: 'Lê Kim Ngọc', classId: 'CLS-G10-01', level: 'Lớp 10' },
  { id: 'STD-006', name: 'Ngô Gia Linh', classId: 'CLS-G09-01', level: 'Lớp 9' },
  { id: 'STD-007', name: 'Bùi Thiên An', classId: 'CLS-G06-01', level: 'Lớp 6' },
  { id: 'STD-008', name: 'Vũ Nhật Hạ', classId: 'CLS-G10-01', level: 'Lớp 10' },
];

export const MOCK_ASSIGNMENTS = [
  {
    id: 'ASN-001',
    code: 'BT-IELTS-RD-001',
    title: 'Reading Matching Headings Unit 3',
    type: 'Bài tập',
    level: 'IELTS',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    totalItems: 5,
    durationMinutes: 25,
    status: 'Đã giao',
    createdAt: '2026-06-25T08:30:00',
    targetClasses: ['CLS-IELTS-01'],
    targetStudents: [],
    studentsDone: 14,
    averageScore: 7.8,
  },
  {
    id: 'ASN-002',
    code: 'EX-G10-WR-002',
    title: 'Viết đoạn văn chủ đề Environment',
    type: 'Đề thi',
    level: 'Lớp 10',
    difficulty: 'Nâng cao',
    skill: 'Viết',
    totalItems: 3,
    durationMinutes: 45,
    status: 'Đã sinh đề',
    createdAt: '2026-06-27T15:15:00',
    targetClasses: [],
    targetStudents: [],
    studentsDone: 0,
    averageScore: 0,
  },
  {
    id: 'ASN-003',
    code: 'BT-TOEIC-LS-003',
    title: 'TOEIC Listening Short Answers Pack A',
    type: 'Bài tập',
    level: 'TOEIC',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    totalItems: 8,
    durationMinutes: 20,
    status: 'Đã giao',
    createdAt: '2026-06-30T09:00:00',
    targetClasses: ['CLS-TOEIC-01'],
    targetStudents: [],
    studentsDone: 18,
    averageScore: 8.4,
  },
  {
    id: 'ASN-004',
    code: 'BT-G09-RD-004',
    title: 'Điền từ vào đoạn văn Unit 5',
    type: 'Bài tập',
    level: 'Lớp 9',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    totalItems: 4,
    durationMinutes: 18,
    status: 'Nháp',
    createdAt: '2026-07-01T11:45:00',
    targetClasses: [],
    targetStudents: [],
    studentsDone: 0,
    averageScore: 0,
  },
  {
    id: 'ASN-005',
    code: 'EX-IELTS-WR-005',
    title: 'IELTS Writing Task 2 Opinion Essay',
    type: 'Đề thi',
    level: 'IELTS',
    difficulty: 'Nâng cao',
    skill: 'Viết',
    totalItems: 2,
    durationMinutes: 60,
    status: 'Đã đóng',
    createdAt: '2026-06-18T13:30:00',
    targetClasses: ['CLS-IELTS-02'],
    targetStudents: [],
    studentsDone: 15,
    averageScore: 6.9,
  },
  {
    id: 'ASN-006',
    code: 'BT-G06-LS-006',
    title: 'Nghe điền từ Unit Family',
    type: 'Bài tập',
    level: 'Lớp 6',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    totalItems: 6,
    durationMinutes: 15,
    status: 'Đã giao',
    createdAt: '2026-07-02T07:50:00',
    targetClasses: ['CLS-G06-01'],
    targetStudents: [],
    studentsDone: 19,
    averageScore: 8.7,
  },
];

export const MOCK_BANK_ITEMS = [
  {
    id: 'BANK-LS-001',
    title: 'Listening Form Completion - School Registration',
    level: 'IELTS',
    difficulty: 'Trung bình',
    skill: 'Nghe',
    questionFormat: 'Trả lời ngắn',
    unit: 'Unit 1',
    childQuestionCount: 6,
    status: 'Sẵn sàng',
    description: 'Bài nghe điền form gồm 6 câu con.',
  },
  {
    id: 'BANK-LS-002',
    title: 'Listening MCQ - Campus Tour',
    level: 'IELTS',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    questionFormat: 'Trắc nghiệm 1 đáp án',
    unit: 'Unit 2',
    childQuestionCount: 5,
    status: 'Sẵn sàng',
    description: 'Bài nghe chọn đáp án đúng theo đoạn hội thoại.',
  },
  {
    id: 'BANK-LS-003',
    title: 'Listening Matching - Holiday Plan',
    level: 'TOEIC',
    difficulty: 'Trung bình',
    skill: 'Nghe',
    questionFormat: 'Nối các phần tương ứng',
    unit: 'Unit 4',
    childQuestionCount: 4,
    status: 'Đang dùng',
    description: 'Nối speaker với ý định phù hợp.',
  },
  {
    id: 'BANK-LS-004',
    title: 'Listening Sentence Completion - Daily Routine',
    level: 'Lớp 6',
    difficulty: 'Cơ bản',
    skill: 'Nghe',
    questionFormat: 'Hoàn thiện câu',
    unit: 'Unit Family',
    childQuestionCount: 6,
    status: 'Sẵn sàng',
    description: 'Nghe và hoàn thiện câu theo chủ đề gia đình.',
  },
  {
    id: 'BANK-RD-001',
    title: 'Reading Matching Headings - Urban Life',
    level: 'IELTS',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    questionFormat: 'Trắc nghiệm 1 đáp án',
    unit: 'Unit 3',
    childQuestionCount: 5,
    status: 'Sẵn sàng',
    description: 'Đọc hiểu dạng matching headings.',
  },
  {
    id: 'BANK-RD-002',
    title: 'Gap-fill Passage - Climate Change',
    level: 'Lớp 9',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    questionFormat: 'Điền từ vào chỗ trống/khuyết',
    unit: 'Unit 5',
    childQuestionCount: 8,
    status: 'Sẵn sàng',
    description: 'Đoạn văn điền khuyết về biến đổi khí hậu.',
  },
  {
    id: 'BANK-RD-003',
    title: 'Reading Short Answer - Company Memo',
    level: 'TOEIC',
    difficulty: 'Cơ bản',
    skill: 'Đọc',
    questionFormat: 'Trả lời ngắn',
    unit: 'Unit 7',
    childQuestionCount: 5,
    status: 'Đang dùng',
    description: 'Đọc memo và trả lời ngắn.',
  },
  {
    id: 'BANK-RD-004',
    title: 'Insert Sentence - Technology in Classrooms',
    level: 'IELTS',
    difficulty: 'Nâng cao',
    skill: 'Đọc',
    questionFormat: 'Chèn câu vào đoạn văn',
    unit: 'Unit 6',
    childQuestionCount: 4,
    status: 'Nháp',
    description: 'Chèn câu vào vị trí hợp lý trong đoạn văn.',
  },
  {
    id: 'BANK-RD-005',
    title: 'Word Form - Healthy Lifestyle',
    level: 'Lớp 10',
    difficulty: 'Trung bình',
    skill: 'Đọc',
    questionFormat: 'Cho dạng đúng của từ',
    unit: 'Unit 2',
    childQuestionCount: 7,
    status: 'Sẵn sàng',
    description: 'Biến đổi từ theo ngữ cảnh đoạn văn.',
  },
  {
    id: 'BANK-WR-001',
    title: 'Sentence Writing - My School',
    level: 'Lớp 6',
    difficulty: 'Cơ bản',
    skill: 'Viết',
    questionFormat: 'Viết câu',
    unit: 'Unit School',
    childQuestionCount: 5,
    status: 'Sẵn sàng',
    description: 'Viết câu hoàn chỉnh từ gợi ý cho trước.',
  },
  {
    id: 'BANK-WR-002',
    title: 'Paragraph Writing - Protect the Environment',
    level: 'Lớp 10',
    difficulty: 'Trung bình',
    skill: 'Viết',
    questionFormat: 'Viết đoạn văn',
    unit: 'Unit 8',
    childQuestionCount: 1,
    status: 'Sẵn sàng',
    description: 'Viết đoạn văn 120-150 từ.',
  },
  {
    id: 'BANK-WR-003',
    title: 'Opinion Essay - Online Learning',
    level: 'IELTS',
    difficulty: 'Nâng cao',
    skill: 'Viết',
    questionFormat: 'Viết bài luận',
    unit: 'Unit 9',
    childQuestionCount: 1,
    status: 'Đang dùng',
    description: 'Task 2 dạng opinion essay.',
  },
  {
    id: 'BANK-WR-004',
    title: 'Sentence Transformation - Relative Clauses',
    level: 'Lớp 9',
    difficulty: 'Trung bình',
    skill: 'Viết',
    questionFormat: 'Viết lại câu',
    unit: 'Unit 4',
    childQuestionCount: 6,
    status: 'Sẵn sàng',
    description: 'Viết lại câu sử dụng mệnh đề quan hệ.',
  },
  {
    id: 'BANK-LS-005',
    title: 'Listening Multiple Choice - Hotel Booking',
    level: 'TOEIC',
    difficulty: 'Trung bình',
    skill: 'Nghe',
    questionFormat: 'Trắc nghiệm nhiều đáp án',
    unit: 'Unit 6',
    childQuestionCount: 5,
    status: 'Sẵn sàng',
    description: 'Chọn nhiều đáp án đúng trong đoạn hội thoại.',
  },
  {
    id: 'BANK-RD-006',
    title: 'Error Correction - School Rules',
    level: 'Lớp 10',
    difficulty: 'Cơ bản',
    skill: 'Đọc',
    questionFormat: 'Tìm và sửa lỗi sai',
    unit: 'Unit 1',
    childQuestionCount: 6,
    status: 'Sẵn sàng',
    description: 'Tìm và sửa lỗi sai trong câu.',
  },
];
